name: Build and Deploy Script
on:
  push:
    branches:
    - training

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22.15.1
    - name: Install Dependencies
      run: npm install
    - name: Run tests
      run: npm run test:ci
    - name: Build Angular App
      run: npm run build
    - name: Deploy to Pages
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: /angular-template/
        deploy_branch: gh-pages 
        angular_dist_build_folder: dist/angular-template/browser

permissions:
  contents: write

