name: Build and Deploy Script
on:
  push:
    branches:
    - main
    - training/*

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22.15.1
    - name: Install Dependencies
      run: npm install
    - name: Build Angular App
      run: npm run build
    - name: Deploy to Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: dist/angular-template
